### PR TITLE
Transforming

### PR DESCRIPTION
**Pull request by jenncasper**
Uri,

This is the Exercise 1 Part 2 and Part 3 submission that is now 12 hours and 14 minutes late. I would like to use one of the two late days for this submission, per the course policy you noted in the latest upload.

There is one file in the transforming directory that covers all transforms needed for Part 2 of exercise 1. It should run for you using hive -f hive_transforms_ddl.sql assuming the hive_base_ddl.sql under loading_and_modelling was executed.

The investigations directory contains the four sub-directories per the exercise1.pdf - best_hospitals, best_states, procedure_variability, and hospitals_and_patients. Each subdirectory contains the sql file to run using hive -f. The associated .txt file contains an explanation of the approach, results, and discussion.

This all is the result of a significant amount of thrashing and learning. My notes.txt files was full of command, approaches, and results that all evolved into what I'm submitting now.

Thank you for your time and please let me know what I missed or if something isn't working for you.

Sincerely,

Jenn

### CODE REVIEW

**Comment by neuralinfo** [comment]
Seems you have sent this to the wrong github account. Double check with
your instructors about where to send the pull request.

A.

---------- Forwarded message ----------

**Comment by jenncasper** [comment]
A - I apologize for the confusion. I assigned the pull request to shuri-w205 and I'm not sure how it got routed to you. I will confirm with the instructor.

**Comment by shuri-w205** [comment]
No worries Jenn!
I think you assigned correctly to me but you still have 3 participants on the pull request https://github.com/jenncasper/mids_w205_exercise1/pull/2#issuecomment-252727112.

I think Arash needs to unsubscribe http://stackoverflow.com/questions/30120214/how-can-i-remove-a-participant-from-a-github-pull-request in this case.

Thank you both,
Uri

Either mids-w205 is still a collaborator or ids-w205 is still watching?

**Comment by shuri-w205** [comment]
received (one day late, using 1 day late),

**Pull request merged**
